### ISSUE TITLE
Supports ```javascript but not ```js?

### ISSUE THREAD

**Issue by ljharb** [reggi/evalmd#1]
It seems like this only evaluates \`\`\`javascript blocks, not \`\`\`js blocks. Both are valid in GFM.

**Comment by reggi** [comment]
works for me with https://github.com/reggi/evalmd/commit/d9b54ea5635ccb7fef68dc7fb1fd4e52350a5302

**Comment by reggi** [comment]
Thanks a bunch for finding this, btw! Let me know if you run into any other bugs. Just pushed to npm 0.0.3. https://www.npmjs.com/package/evalmd
