### ISSUE TITLE
avoid `npm audit` error

### ISSUE THREAD

**Issue by ljharb** [reggi/evalmd#13]
`npm audit` complains about the version of lodash you're using here. Could you remove lodash, or update to lodash 4 latest, and publish a release?

**Comment by reggi** [comment]
@ljharb Just dug into this seems to be a module I'm using `acorn-umd`. I forked the repo and am trying to simply `npm install` and it's giving me issues. Might need to swap out this dep.

https://github.com/reggi/acorn-umd/blob/master/package.json#L62

**Comment by ljharb** [comment]
Could you use real acorn, instead of some UMD fork?

**Comment by reggi** [comment]
It's a function that allows me to get the dependencies without traversing the tree myself. It's a pain just tried to do it without it, not a quick fix. Also tried to fix `acorn-umd`'s deps and it's a rabbit hole.

**Comment by ljharb** [comment]
@reggi you're directly depending on lodash 3: https://github.com/reggi/evalmd/blob/master/package.json#L29 it seems like you could update that without dealing with acorn-umd?

**Comment by reggi** [comment]
Hey @ljharb I just updated lodash. Can you confirm everything is working smoothly, I'm basing regressions on just running `readme.md`.

**Comment by ljharb** [comment]
Absolutely, I’ll let you know after checking a bunch of repos :-) thanks!

**Comment by reggi** [comment]
🙇 Thanks for the ping.

**Comment by ljharb** [comment]
so, nothing's broken, which is great! but sadly there's still an audit report, as you indicated, due to `acorn-umd` and *its* lodash version.

It'd be great to swap that out; I'm not clear on why UMD anything would be needed anyways.

**Comment by reggi** [comment]
@ljharb I tried updating it with the intention of publishing my own version without the problematic lodash version however there are many of it's deps that are outdated, and issues arise when I update everything. 

I just tried once more and when I pull down the code acorn-umd, run  `npm i` and the `build` script it fails.

The only simple-option without removing acorn-umd entirely I can think of is to make a complete bundle of `acorn-umd` like a rolled up version, include that in this source, and remove the dep entirely.

**Comment by ljharb** [comment]
What’s it used for exactly?

**Comment by reggi** [comment]
@ljharb AST parsing for JS it allows a really simple interface to detect `require` and `import` in JS, so I can bundle the dependency in markdown, and support both formats.

**Comment by ljharb** [comment]
Would filing an issue on acorn-umd about their lodash dep help?

**Comment by reggi** [comment]
It can't hurt.

**Comment by ljharb** [comment]
https://github.com/megawac/acorn-umd/issues/7

**Comment by reggi** [comment]
@ljharb OK just went wild and added the source files from og `acorn-umd` into this repo with ts support. Tried to publish beta version to npm and used tag flag, didn't work so there's a 0.0.19 version out there. It works for me locally.

**Comment by reggi** [comment]
@ljharb hmm i have no clue what I'm doing, so I guess the flag did work. B/c npm still has 0.0.18 but you can install 0.0.19 directly. https://www.npmjs.com/package/evalmd

> yarn global add evalmd@0.0.19

oh the woes of beeing a package maintainer.

**Comment by ljharb** [comment]
Cool, I’ll try that

**Comment by ljharb** [comment]
@reggi if you run `npm dist-tag add evalmd@0.0.19 latest` it will allow it to be installed by default, and then this can be closed :-)

(also if you wanted to add me to the repo and npm package, i'd be happy to help maintain it)
